#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

if (!defined('CROOK_PROJECT_ROOT')) {
    define('CROOK_PROJECT_ROOT', __DIR__ . '/');
}

$app = new Crook\Application(new Crook\Config);

try {
    $result = $app->run();
} catch (\Exception $e) {
    exit(23);
}

echo $result['message'];
exit($result['code']);

