#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use Crook\Application;
use Crook\Config;

$app = new Application(
    new Config(dirname(__FILE__, 2)),
    basename(__FILE__)
);

$result = $app->run();

echo $result['message'];
//exit($result['code']);

