#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use Crook\Application;
use Crook\Config;

$app = new Application(
    new Config(dirname(__FILE__, 2)),
    basename($argv[0])
);

try {
    $result = $app->run();
} catch (\Exception $e) {
    exit(23);
}

echo $result['message'];
exit($result['code']);

